name: Laileme
options:
  bundleIdPrefix: com.laileme
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"

targets:
  Laileme:
    type: application
    platform: iOS
    sources:
      - path: Laileme
        excludes:
          - Info.plist
    info:
      path: Laileme/Info.plist
      properties:
        CFBundleDisplayName: Laileme
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.laileme.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: Laileme/Info.plist
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
